<?php

class Layout {

    function show_menu($UserName) {
        $obj = & get_instance();
        $obj->load->helper('url');

        $menu ='<ul>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='          <span class="menu-mid">Catalog</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='       <div class = "sub">';
        $menu .='           <ul>';
        $menu .='               <li>';
        $menu .='                   <a href="' . base_url() . 'index.php/Catalog/prodcat/" target="_self">Product Catalog</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href="' . base_url() . 'index.php/Catalog/configurator/" target="_self">Configurator(CSR)</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href="' . base_url() . 'index.php/Catalog/costs/" target="_self">Inventory Cost</a>';
        $menu .='               </li>';
        $menu .='           </ul>';
        $menu .='           <div class = "btm-bg"></div>';
        $menu .='       </div>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Orders</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='       <div class = "sub">';
        $menu .='           <ul>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Orders/omc/" target = "_self">Order Management Center</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Orders/bc/" target = "_self">Billing Center</a>';
        $menu .='               </li>';
        $menu .='           </ul>';
        $menu .='           <div class = "btm-bg"></div>';
        $menu .='       </div>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .= '          <span class = "menu-mid">Reports</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='       <div class = "sub">';
        $menu .='           <ul>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/excessinventory/" target = "_self">Excess Inventory</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/pendingfbareport/" target = "_self">Pending FBA Report</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/pendingorders/" target = "_self">Pending Orders</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/salesbysku/" target = "_self">Sales by SKU</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/projectorlampleads/" target = "_self">Projector Lamp Leads</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/suppliercost/" target = "_self">Supplier Cost</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/asinlist/" target = "_self">ASIN List</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/amazontophilips/" target = "_self">AmazonASIN to PhilipsSKU</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/fbmreportbyqtysold/" target = "_self">FBM Report by Qty Sold</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/adjustmentdetails/" target = "_self">Adjustment Details</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/lampsoutofstock/" target = "_self">Lamps Out Of Stock</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/receivedinventory/" target = "_self">Received Inventory</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Reports/globalinventory/" target = "_self">Global Inventory</a>';
        $menu .='               </li>';
        $menu .='           </ul>';
        $menu .='           <div class = "btm-bg"></div>';
        $menu .='       </div>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Tools</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='       <div class = "sub">';
        $menu .='           <ul>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Console/myconsole/" target = "_self">Console</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/buyonline/" target = "_self">BuyOnLine</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/dropshipssold/" target = "_self">Drop Ships Sold</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/serialscapture/" target = "_self">Serials Capture</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/amazonfba/" target = "_self">Amazon FBA</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/datamining/" target = "_self">Channel Data Mining</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/Schools/school/" target = "_self">Schools</a>';
        $menu .='               </li>';
	$menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/tools/youtubevideos/" target = "_self">Youtube Videos</a>';
        $menu .='               </li>';	
        $menu .='           </ul>';
        $menu .='           <div class = "btm-bg"></div>';
        $menu .='       </div>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Settings</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a href = "http://dir.mitechnologiesinc.com" target = "_blank">';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Company Dir</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a>';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Dashboard</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='       <div class = "sub">';
        $menu .='           <ul>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/dashboard/sales/" target = "_self">Sales Reports</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/dashboard/dropship/" target = "_self">Dropship Reports</a>';
        $menu .='               </li>';
        $menu .='               <li>';
        $menu .='                   <a href = "' . base_url() . 'index.php/dashboard/csr/" target = "_self">Customer Service</a>';
        $menu .='               </li>';
        $menu .='           </ul>';
        $menu .='           <div class = "btm-bg"></div>';
        $menu .='       </div>';
        $menu .='   </li>';
        $menu .='   <li class = "#">';
        $menu .='       <a href = "' . base_url() . 'index.php/welcome/logout/" target = "_self">';
        $menu .='           <span class = "menu-left"></span>';
        $menu .='           <span class = "menu-mid">Logout</span>';
        $menu .='           <span class = "menu-right"></span>';
        $menu .='       </a>';
        $menu .='   </li>';
        $menu .='</ul>';
        $menu .='<div class = "user">';
        $menu .='   Welcome:<b>'.$UserName["FullName"];
        $menu .='</div>';
        
        return $menu;
    }
}
?>